name: Publish Module Release
description: 'Publish Module Release'
inputs:
  version:
    description: 'Version'
    required: true
  description:
    description: 'Release Description'
    required: true
    default: "To install this module, download it below and extract it over your Pragma installation."
  token:
    description: 'Secret Token'
    required: true
runs:
  using: "composite"
  steps:
      - name: Get latest Windows Version
        id: windows-version
        shell: bash
        run:   |
          wget https://github.com/$GITHUB_REPOSITORY/releases/download/latest/binaries_windows64.zip
          echo "filename=binaries_windows64.zip" >> $GITHUB_OUTPUT
          
      - name: Get latest Linux Version
        id: linux-version
        shell: bash
        run:   |
          wget https://github.com/$GITHUB_REPOSITORY/releases/download/latest/binaries_linux64.tar.gz
          echo "filename=binaries_linux64.tar.gz" >> $GITHUB_OUTPUT

      - name: Generate release description
        shell: bash
        run:   |
          curDate=$(date -u '+%Y-%m-%d %H:%M:%S %Z')
          desc="Latest release date: $curDate\n\n${{ inputs.description }}"
          printf "$desc" > body_text.txt
      
      - name: Update tag description
        uses: softprops/action-gh-release@v0.1.14
        with:
          body_path: body_text.txt
          tag_name: "v${{ inputs.version }}"
          prerelease: false

      - name: Publish Windows Release
        uses: pyTooling/Actions/releaser/composite@main
        with:
          tag: "v${{ inputs.version }}"
          rm: true
          token: ${{ inputs.token }}
          files: ${{ steps.windows-version.outputs.filename }}
            
      - name: Publish Linux Release
        uses: pyTooling/Actions/releaser/composite@main
        with:
          tag: "v${{ inputs.version }}"
          token: ${{ inputs.token }}
          files: ${{ steps.linux-version.outputs.filename }}
